apiVersion: apps/v1
kind: Deployment
metadata:
  name: posting-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posting
  template:
    metadata:
      labels:
        app: posting
    spec:
      containers:
        - name: posting
          image: iamrahulrnair/posting
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://posting-mongo-srv:27017/posting'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: posting-srv
spec:
  selector:
    app: posting
  type: ClusterIP
  ports:
    - name: posting
      protocol: TCP
      port: 3000
      targetPort: 3000
