apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-queue-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-queue
  template:
    metadata:
      labels:
        app: post-queue
    spec:
      containers:
        - name: post-queue
          image: iamrahulrnair/post_queue
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://post-queue-mongo-srv:27017/post-queue'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: post-queue-srv
spec:
  selector:
    app: post-queue
  type: ClusterIP
  ports:
    - name: post-queue
      protocol: TCP
      port: 3000
      targetPort: 3000
